spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        css: text/css 